### ISSUE TITLE
Desenvolver a parte do Create do CRUD.

### ISSUE THREAD

**Issue by eonarga** [GRUPO-Grrap/Lista-de-Compras#1]
Create

Trata-se do conceito de criação, registro ou cadastro de informações e dados em um determinado lugar.
Sendo assim, pode se referir à criação de dados de uma tabela, ao registro da lista do item de compra na lista.

Documentar processo

**Comment by lucascampolimm** [comment]
Ok.

[doc.txt](https://github.com/GRUPO-Grrap/Lista-de-Compras/files/14643278/doc.txt)
